/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: Karolina Renkiewicz (https://sketchfab.com/KarolinaRenkiewicz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bitcoin-ff17dab54b044d789d05ae7c8dfb9808
Title: Bitcoin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002__0.geometry} material={materials['Scene_-_Root']} position={[-3.489, 36.23, -11.294]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
