/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: tonyflanagan (https://sketchfab.com/tonyflanagan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-worker-6-animated-09691ea4303348a79d2b68ba22bc5a59
Title: Office Worker 6 - Animated
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3D-Model/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.947}>
          <group name="a4ef048fbe664e1387d2818f70597959fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="computer_chair" position={[-15.032, 2.248, 8.764]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="computer_chair_CHAIR_0" geometry={nodes.computer_chair_CHAIR_0.geometry} material={materials.CHAIR} />
                </group>
                <group name="Floor" rotation={[-Math.PI / 2, 0, 0]} scale={350}>
                  <mesh name="Floor_Wood_0" geometry={nodes.Floor_Wood_0.geometry} material={materials.Wood} />
                </group>
                <group name="Table" position={[-15.196, -1.354, 59.981]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Table_STEEL_0" geometry={nodes.Table_STEEL_0.geometry} material={materials.STEEL} />
                </group>
                <group name="mouse" position={[-30.478, 73.052, 57.046]} rotation={[-Math.PI / 2, 0, -3.14]} scale={184.863}>
                  <mesh name="mouse_STEEL_0" geometry={nodes.mouse_STEEL_0.geometry} material={materials.STEEL} />
                </group>
                <group name="Armature">
                  <group name="Object_13">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_93" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_95" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_97" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_99" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_101" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_103" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_105" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_107" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_109" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_111" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.body} skeleton={nodes.Object_94.skeleton} />
                    <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.bottom} skeleton={nodes.Object_96.skeleton} />
                    <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.eyes} skeleton={nodes.Object_98.skeleton} />
                    <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.eyes} skeleton={nodes.Object_100.skeleton} />
                    <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.glasses} skeleton={nodes.Object_102.skeleton} />
                    <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.hair} skeleton={nodes.Object_104.skeleton} />
                    <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.head} skeleton={nodes.Object_106.skeleton} />
                    <skinnedMesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.shoes} skeleton={nodes.Object_108.skeleton} />
                    <skinnedMesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.teeth} skeleton={nodes.Object_110.skeleton} />
                    <skinnedMesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material} skeleton={nodes.Object_112.skeleton} />
                  </group>
                </group>
                <group name="body" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="bottom" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="eye_left" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="eye_right" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="glasses" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="hair" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="head" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="shoes" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="teeth" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="top" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3D-Model/scene.gltf')
