/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: Oleg Muzyka (https://sketchfab.com/olemuzyka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-5ee15da877a84df3aade63344d9fc1a4
Title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.aiStandardSurface5SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.aiStandardSurface7SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.aiStandardSurface1SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.aiStandardSurface3SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.aiStandardSurface4SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.aiStandardSurface4SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.aiStandardSurface4SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.aiStandardSurface6SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.initialShadingGroup} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
